---
- name: "PREINSTALL | Set repo"
  set_fact:
    source: "{{ urls[input_source] }}"

- name: "PREINSTALL | Get content host"
  shell: "cat /etc/hosts"
  register: hosts

- name: "PREINSTALL | Generate ansible_hosts lines"
  set_fact:
    hosts_lines: "{{ hosts_lines }}\n{{hostvars[item].ansible_default_ipv4.address}}  node{{my_idx+1}} {{hostvars[item].ansible_hostname}} {{hostvars[item].ansible_nodename}} {{hostvars[item].ansible_fqdn}}"
  loop: "{{ ansible_play_hosts }}"
  loop_control:
    index_var: my_idx
  run_once: true
  delegate_to: localhost

- name: "PREINSTALL | Combine original hosts and ansible hosts"
  set_fact:
    hosts_lines: "{{ hosts.stdout }}\n{{ hosts_lines }}"

- name: "PREINSTALL | Update /etc/hosts"
  copy:
    content: "{{ hosts_lines }}"
    dest: "/etc/hosts"